/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'
import { Route as AdminSlideshowRouteImport } from './routes/admin/slideshow'
import { Route as LiveMatchIdRouteImport } from './routes/live.$matchId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as RefereeMatchIdRouteImport } from './routes/referee.$matchId'
import { Route as CommentateMatchIdRouteImport } from './routes/commentate.$matchId'
import { Route as ModeratorMatchIdRouteImport } from './routes/moderator.$matchId'
import { Route as LeaguesSlugRouteImport } from './routes/leagues.$slug'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DashboardLeaguesRouteImport } from './routes/dashboard/leagues'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlideshowRoute = AdminSlideshowRouteImport.update({
  id: '/slideshow',
  path: '/slideshow',
  getParentRoute: () => AdminRoute,
} as any)
const LiveMatchIdRoute = LiveMatchIdRouteImport.update({
  id: '/live/$matchId',
  path: '/live/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeMatchIdRoute = RefereeMatchIdRouteImport.update({
  id: '/referee/$matchId',
  path: '/referee/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentateMatchIdRoute = CommentateMatchIdRouteImport.update({
  id: '/commentate/$matchId',
  path: '/commentate/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorMatchIdRoute = ModeratorMatchIdRouteImport.update({
  id: '/moderator/$matchId',
  path: '/moderator/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LeaguesRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaguesRoute = DashboardLeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRoute
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRoute
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/matches': typeof MatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/leagues': typeof LeaguesRouteWithChildren
  '/live': typeof LiveRoute
  '/dashboard/leagues': typeof DashboardLeaguesRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/leagues/$slug': typeof LeaguesSlugRoute
  '/matches/$id': typeof MatchesIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/matches/': typeof MatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/leagues'
    | '/live'
    | '/dashboard/leagues'
    | '/dashboard/teams'
    | '/leagues/$slug'
    | '/matches/$id'
    | '/dashboard/'
    | '/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/leagues'
    | '/live'
    | '/dashboard/leagues'
    | '/dashboard/teams'
    | '/leagues/$slug'
    | '/matches/$id'
    | '/dashboard'
    | '/matches'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/leagues'
    | '/live'
    | '/dashboard/leagues'
    | '/dashboard/teams'
    | '/leagues/$slug'
    | '/matches/$id'
    | '/dashboard/'
    | '/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LeaguesRoute: typeof LeaguesRouteWithChildren
  LiveRoute: typeof LiveRoute
  LiveMatchIdRoute: typeof LiveMatchIdRoute
  MatchesIdRoute: typeof MatchesIdRoute
  RefereeMatchIdRoute: typeof RefereeMatchIdRoute
  CommentateMatchIdRoute: typeof CommentateMatchIdRoute
  ModeratorMatchIdRoute: typeof ModeratorMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof LeaguesRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leagues': {
      id: '/dashboard/leagues'
      path: '/leagues'
      fullPath: '/dashboard/leagues'
      preLoaderRoute: typeof DashboardLeaguesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminSlideshowRoute: typeof AdminSlideshowRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute,
  AdminUsersRoute,
  AdminModerationRoute,
  AdminPaymentsRoute,
  AdminAdsRoute,
  AdminSlideshowRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardLeaguesRoute: typeof DashboardLeaguesRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLeaguesRoute: DashboardLeaguesRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LeaguesRouteChildren {
  LeaguesSlugRoute: typeof LeaguesSlugRoute
}

const LeaguesRouteChildren: LeaguesRouteChildren = {
  LeaguesSlugRoute: LeaguesSlugRoute,
}

const LeaguesRouteWithChildren =
  LeaguesRoute._addFileChildren(LeaguesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LeaguesRoute: LeaguesRouteWithChildren,
  LiveRoute: LiveRoute,
  LiveMatchIdRoute: LiveMatchIdRoute,
  MatchesIdRoute: MatchesIdRoute,
  RefereeMatchIdRoute: RefereeMatchIdRoute,
  CommentateMatchIdRoute: CommentateMatchIdRoute,
  ModeratorMatchIdRoute: ModeratorMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
